### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by ArcanusNEO** [vinceliuice/WhiteSur-gtk-theme#1035]
![截图 2024-03-24 20-13-07](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/57259186/4e0ac869-0e0b-4245-b0b7-0a2565e7a8dd)

![截图 2024-03-24 20-13-27](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/57259186/4e268d0c-35db-46ad-bb3c-353643b889ab)

Arch Linux
GNOME Shell 46.0
aur/whitesur-gtk-theme-git

Icons have wrong dark background.

**Comment by xuanruiqi** [comment]
Also, since I believe GNOME Shell changed something about notifications, notifications are not displayed correctly.

**Comment by ArcanusNEO** [comment]
Alt+Tab is also broken

**Comment by See-Night** [comment]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/45226780/94ae0263-3208-4189-b316-243c58c8358a)
![截图 2024-03-25 14-14-05](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/45226780/590043f6-a492-4077-86c7-084bbbaab96d)
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/45226780/86005251-eee9-403b-8351-8d956698694a)


1. GTK input panel(?) have white border
2. Application folder looked crowded
3. Applications in folder have wrong background color

> Arch Linux
> Gnome Shell 46

**Comment by xuanruiqi** [comment]
Yes, almost all light themes are having this problem as of GNOME 46.

**Comment by deathblade287** [comment]
Will this be fixed by the theme developers or the gnome team? (i.e. is this a theme specific issue or a gnome/gtk issue)

**Comment by xuanruiqi** [comment]
@deathblade287 : No, this is simply an API change.

**Comment by RashadGasimli** [comment]
don't use this theme for libadwaita (not perfect), use normal installation method and use with blur-my-shell

**Comment by vinceliuice** [comment]
Fixed now

**Comment by ArcanusNEO** [comment]
Thank you very much!
But I think Alt+Tab is still not displayed correctly.

![图片](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/57259186/a459ad58-072d-4dfb-8be9-cc43a35424b3)

**Comment by vinceliuice** [comment]
Fixed

**Comment by dagimg-dot** [comment]
> For me I just used normal installation (AUR package), exported GTK_THEME=WhiteSur-Light and set the WhiteSur-Light theme in gnome-tweaks.

what do you mean exported GTK_THEME

**Comment by ArcanusNEO** [comment]
> > For me I just used normal installation (AUR package), exported GTK_THEME=WhiteSur-Light and set the WhiteSur-Light theme in gnome-tweaks.
> 
> what do you mean exported GTK_THEME

echo 'export GTK_THEME=WhiteSur-Light' >>~/.xprofile
