### ISSUE TITLE
Changing the GNOME40 activities background

### ISSUE THREAD

**Issue by behren** [vinceliuice/WhiteSur-gtk-theme#212]
Hello, I installed Fedora 34 (GNOME 40) today and gave this theme a try. So far it works but I can't figure out how to change the background of the activities overview. I am talking about the BigSur Wallpaper behind my own here:

![image](https://user-images.githubusercontent.com/75254846/116465916-296fe500-a86e-11eb-9552-11e30093539d.png)

Can you help me out?

**Comment by rstrube** [comment]
I've also opened up #201 which requests the ability to change the wallpaper (or just use the selected wallpaper) for the activities overview.

**Comment by vinceliuice** [comment]
Just install this: https://extensions.gnome.org/extension/3193/blur-my-shell/
Thene you will get what you want!

**Comment by vinceliuice** [comment]
Now you can put a image at source root dir, and run `./install.sh -b [your image name]`  for example: `./install.sh -b background.jpg`

**Comment by behren** [comment]
Yea, i was looking for the same solution as described in #201 not for an option to blur the shell or to change the GDM background.

**Comment by vinceliuice** [comment]
Now it's OK

**Comment by KonstantMan** [comment]
When i try this it only changes the themes and not the background image 
![Screenshot from 2021-06-15 15-38-39](https://user-images.githubusercontent.com/56481040/122053805-9c113180-cdd6-11eb-849f-115b96b7c82a.png)

**Comment by rivanfebrian123** [comment]
What about `sudo ./tweaks.sh -g -b "<your background>"`?

**Comment by KonstantMan** [comment]
That changes  only  the GDM background

**Comment by KonstantMan** [comment]
> Now you can put a image at source root dir, and run `./install.sh -b [your image name]` for example: `./install.sh -b background.jpg`

Any ideas why this doesn't work anymore ?

**Comment by vinceliuice** [comment]
Fixed!

**Comment by KonstantMan** [comment]
> Fixed!

I have the exact same problem it changes the themes but not the activities background

**Comment by vinceliuice** [comment]
I tested it on my manjaro gnome40, it's fixed now

**Comment by KonstantMan** [comment]
Unless you are on a developers build manjaro doesn't support gnome 40 shell for now only applications

**Comment by KonstantMan** [comment]
I just installed the latest version it still doesn't work for Arch GNOME 40 
![Screenshot from 2021-07-09 04-04-29](https://user-images.githubusercontent.com/56481040/125008210-8ef00700-e051-11eb-97f3-9c52de736d36.png)

**Comment by vinceliuice** [comment]
Sorry! Currently only supports png files

**Comment by vinceliuice** [comment]
You can first convert to png format and then try
