### ISSUE TITLE
GDM theme broke, dark theme shell gone, top bar font got bolder again

### ISSUE THREAD

**Issue by hematenergi** [vinceliuice/WhiteSur-gtk-theme#246]
![image](https://user-images.githubusercontent.com/47767846/118353555-02fdb980-b591-11eb-8a6d-f31351f7092f.png)
after trying to change gnome gdm theme to default background theme and suddenly broke like this. im on ubuntu 20.04 
![image](https://user-images.githubusercontent.com/47767846/118355462-51fc1c80-b59a-11eb-98f2-4bb23bc295d3.png)

**Comment by hematenergi** [comment]
![image](https://user-images.githubusercontent.com/47767846/118353799-24ab7080-b592-11eb-9e58-d8827b8629c0.png)
now, top bar font got bigger and bold again, also dark theme shell is same style with light theme. its the big broke since last error i reported

**Comment by vinceliuice** [comment]
what you run at terminal？ did you add -HD option？

**Comment by anishkumar127** [comment]
ubuntu 21.04 wayland gnome 3.38 . there also broken login screen lock screen total broken. showing only black and bigger icon in black color. and my mostly system broken. after install. gdm   sudo ./tweaks.sh -g -D   
-_- what should i do now ?
i think i have to format my laptop or install new os -_- can u help me ?

**Comment by hematenergi** [comment]
> what you run at terminal？ did you add -HD option？

Command that run the change gdm style and background. 

Now i revert to stable release, everything back to normal but top bar font still bold. Can u show me how to change back the top bar font to normal?

**Comment by hematenergi** [comment]
> ubuntu 21.04 wayland gnome 3.38 . there also broken login screen lock screen total broken. showing only black and bigger icon in black color. and my mostly system broken. after install. gdm sudo ./tweaks.sh -g -D
> -_- what should i do now ? i think i have to format my laptop or install new os -_- can u help me ?

Me too, alternatif you can download latest stable commit. But in my case top bar font get bold after install.

**Comment by vinceliuice** [comment]
Fixed! now

**Comment by hematenergi** [comment]
> Fixed! now

it only fixed broken on applying gdm theme. 
still need to be fixed soon:
1. dark theme still gone (every dark theme i choose still have a white style like a light theme)
2. still have a top bar bold font weight

**Comment by hematenergi** [comment]
> > Fixed! now
> 
> it only fixed broken on applying gdm theme.
> still need to be fixed soon:
> 
> 1. dark theme still gone (every dark theme i choose still have a white style like a light theme)
> 2. still have a top bar bold font weight, please revert to yaru like font weight because its look more minimal.
>    ![image](https://user-images.githubusercontent.com/47767846/118379632-e354a880-b605-11eb-8057-952b723a8687.png)

please bring back #224 commit

**Comment by nnishant776** [comment]
> dark theme still gone (every dark theme i choose still have a white style like a light theme)

For me, this problem started appearing in commits after 'Fixed #237'.

**Comment by vinceliuice** [comment]
Finally fixed this issue, ubuntu using older version of scss, so the latest update scss file structure cannot be compiled successfully, I can only use the previous file structure

**Comment by vinceliuice** [comment]
I tested on ubuntu 20.04, it's fixed now

**Comment by nnishant776** [comment]
Yes. Working well on manjaro too! Thanks!

**Comment by fd6130** [comment]
I got the same issue , will try this update tmr.

**Comment by hematenergi** [comment]
> I tested on ubuntu 20.04, it's fixed now



> I tested on ubuntu 20.04, it's fixed now

everything great again for now! thank you so much
![image](https://user-images.githubusercontent.com/47767846/118409913-f6738100-b6b6-11eb-93e5-26ec8c7b87b9.png)

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by fd6130** [comment]
The problem has been solved. I think this issue may close for now.

**Comment by vinceliuice** [comment]
Ok
