### ISSUE TITLE
WhiteSur-dark: nautilus side bar artifacts

### ISSUE THREAD

**Issue by vonschutter** [vinceliuice/WhiteSur-gtk-theme#80]
When moving the mount up and down the nautilus sidebar artifact remains long after. This is visually distracting. The problem does not occur in the non-transparent versions. the Arc theme also has a transparent sidebar in nautilus and does not have this issue. Borrow some code?

![Screenshot from 2020-12-03 10-16-04](https://user-images.githubusercontent.com/34268921/100989750-736bcd80-3551-11eb-89f6-040559fda114.jpeg)

**Comment by vonschutter** [comment]
Moving the mouse... not mount... :)

**Comment by vinceliuice** [comment]
Use the solid version, if you are using nvidia driver then you will have this issue on normal version

**Comment by rahacker2006** [comment]
> Use the solid version, if you are using nvidia driver then you will have this issue on normal version

This work for me. Thanks

**Comment by Yuri6037** [comment]
Hi I have the exact same bug. Do you know why it occurs?

Using the solid version is not a solution as it also will make the GNOME top bar look solid.

**Comment by vinceliuice** [comment]
nvidia driver problem, there will be stagnation and residue when changing or moving colors

**Comment by Yuri6037** [comment]
Why is it working fine in other themes? Why is a 3D game able to properly render transparency if it is a NVIDIA problem?

**Comment by vinceliuice** [comment]
I tested it. This issue only occurs when the nautilus background uses a picture. It’s okay to set it to pure color. In order to achieve the same effect as big sur, I set a picture on nautilus as the background. and opnly the Nvidia graphics card driver has this problem, but the Intel and AMD do not have this issue, I've tried various methods, but as long as I want to achieve the same visual effect as big sur, this issue cannot be avoided unless I give up this design.

**Comment by Yuri6037** [comment]
Could you at least enable transparency on GNOME panels but disable transparency in Nautilus as a workarround?

Because KDE can achieve transparency properly with NVIDIA I think there might be a missing re-rendering call missing in Nautilus or GTK.

**Comment by Yuri6037** [comment]
Wait I fixed the problem! This is clearly not a NVIDIA bug: when you make the folder list a little bit smaller the bug disappears completely. Why?

**Comment by vinceliuice** [comment]
So I make the solid version, this has no transparency sidebar,

**Comment by Yuri6037** [comment]
Yeah but the solid version has no transparent GNOME panel. What I'd like as a workarround in this case is a hybrid mode:

```shell
rm -rf ~/.themes/WhiteSur-light/gtk-3.0
cp -r ~/.themes/WhiteSur-light-solid/gtk-3.0 ~/.themes/WhiteSur-light/
```

After doing this you inherit the solid GTK theme but transparent GNOME shell theme. This hybrid mode has no visible artifacts caused by combination of NVIDIA + GNOME compositor but still has transparency on GNOME panel so it does not look totally awfull and unusable. I just tested it.

**Comment by vinceliuice** [comment]
GTK themes and Gnome Shell themes are separate, so you can use Solid GTK themes and transparency Gnome Shell themes. There is no contradiction

**Comment by MichaelP89** [comment]
Should this now work with the solid theme and NVIDIA drivers?
I did not figured it out in this thread. At least it doesn't work for me:
![Bildschirmfoto vom 2021-01-30 09-19-38](https://user-images.githubusercontent.com/48978558/106351461-96f68e80-62dc-11eb-8d2b-1fd02a54e323.png)

**Comment by vinceliuice** [comment]
@MichaelP89 run `./install.sh -s [sidebarsize]` to change the sidebar size, for example: `./install.sh -s 280` (280 px width)

**Comment by Yuri6037** [comment]
Please note that despite the use of the solid themes there are bugs: the previous and next arrow buttons will also show some artifacts.

You might want to use the compromise I have committed.

It seems the problem is not really a transparency bug but more of a linear-gradient combined with GNOME + NVIDIA bug...

**Comment by iamchriswick** [comment]
@vinceliuice Before I was using this theme (and what a great theme I might add) I was using [EliverLara/Nordic](https://github.com/EliverLara/Nordic), and the had the [exact same issue](https://github.com/EliverLara/Nordic/issues/52), and they solved it via CSS.

**Comment by EncryptedCurse** [comment]
@iamchriswick I commented out all the transitions related to Nautilus sidebar entries in `src/main/gtk-3.0/gtk-light.css` and added `background-image: none` for good measure. The issue is still there.

That being said, I honestly know nothing about GTK theme development or whether I was in fact testing it correctly (I just removed and reinstalled with `install.sh`). It would be great if someone more experienced could take a look at the issue/PR you mentioned.

**Comment by rivanfebrian123** [comment]
Hi everyone, actually I already fixed this issue, you can try to run `./install.sh` here: [Uploading WhiteSur-gtk-theme-backup-Mar-27.zip…]()
You can also run `./install.sh -h` and `./tweaks.sh -h` to try some new features there

**Comment by EncryptedCurse** [comment]
> Hi everyone, actually I already fixed this issue, you can try to run `./install.sh` here:
> [WhiteSur-gtk-theme-backup-Mar-27.zip](https://github.com/vinceliuice/WhiteSur-gtk-theme/files/6214533/WhiteSur-gtk-theme-backup-Mar-27.zip)
> 
> You can also run `./install.sh -h` and `./tweaks.sh -h` to explore some new features there

I haven't tried it yet, but nice!

How did you fix it? Do you plan on submitting a PR?

**Comment by rivanfebrian123** [comment]
> How did you fix it? 

Did some reasearch with gtk-inspector :)

> Do you plan on submitting a PR?

Absolutely, I need 3 about more weeks to finish this
